JumboCode/Jeanne-Geiger

src/api/models.py
Changed race/ethnicity field to be possible to select multiple instead of one
=> fix race options in models

src/dvhrt/settings.py
Set up the Postgres database!!
=> Added postgres database to django setup

src/api/views.py
View 3: Victim Information Gender
View 4: Victim Information Ethnicity
=> Backend Views 3 & 4

src/api/models.py
Updated all IntegerFields to AutoFields for primary ids in models.py
=> Backend Update IDs to Auto in Models

src/api/models.py, src/api/views.py, src/dvhrt/urls.py
Views done. But added attribute in models is acting weird. Would like a look!
=> Backend views1 and 2

src/api/views.py, src/dvhrt/urls.py
Updated View 9 to be like the other views and tested it
=> View 9 Update

src/api/urls.py, src/api/views.py
GET request for cases filtered by community_id
=> get for cases by community

src/api/urls.py, src/api/views.py, src/frontend/src/modules/coords/siteAddCase/index.js, src/frontend/src/modules/coords/siteAddCase/util.js
Get request for one case given a hard-coded case_id at new url.
=> one case get

src/frontend/src/modules/navbar/NavigationBar.css, src/frontend/src/modules/navbar/NavigationBar.js
=> updated navbar, fixed edit glitch

src/frontend/src/modules/admin/adminHomepage/index.js, src/frontend/src/modules/admin/adminViewSite/index.js, src/frontend/src/modules/admin/adminViewSite/styles.css, src/frontend/src/modules/datePopUp/datePopUp.css, src/frontend/src/modules/datePopUp/datePopUp.js, src/frontend/src/modules/filters/date_filter/filter.css, src/frontend/src/modules/filters/date_filter/filter.js, src/frontend/src/modules/filters/date_filter/popup.css, src/frontend/src/modules/filters/date_filter/popup.js
=> Date range picker

src/frontend/src/modules/Back/back.js, src/frontend/src/modules/admin/adminAddSite/index.js, src/frontend/src/modules/admin/adminViewSite/index.js, src/frontend/src/modules/coords/detailView/index.js, src/frontend/src/modules/coords/siteAddCase/index.js
previously, back button put through entire trail (eg: detail view to edit to detail view to add....) when preferred behavior is just to go back to the homepage
=> updated back button to take specific link

src/frontend/src/modules/logIn/index.js, src/frontend/src/modules/logIn/styles.css
=> Updated styling of login page

src/frontend/src/modules/admin/adminViewSite/index.js, src/frontend/src/modules/admin/adminViewSite/styles.css, src/frontend/src/modules/coords/siteOverview/index.js, src/frontend/src/modules/logIn/NotFound.js, src/frontend/src/modules/logIn/styles.css
404 page styling 
Ex. go to https://dvhrt.herokuapp.com/hello to see 404 page. 
Fixed display of community name on adminviewsite
=> 404 page & fixed community name display

src/README.md, src/api/models.py, src/api/serializers.py, src/api/urls.py, src/api/utils.py, src/api/views.py
Updated the README and commented code for all backend files. 
The only code line change is in views.py line 92 where we were missing an authorization check on the GET view.
=> backend readme and commenting

src/api/utils.py
This will allow us to get rid of a single hardcoded default password. The flow will still work the same otherwise.
=> changed default password generation method

src/frontend/src/modules/admin/adminAddSite/styles.css, src/frontend/src/modules/admin/adminManageSite/styles.css, src/frontend/src/modules/admin/adminViewSite/styles.css, src/frontend/src/modules/coords/detailView/styles.css, src/frontend/src/modules/coords/siteAddCase/styles.css
Not sure if this one will work but lets hope for the best
=> Button fixes

src/frontend/src/modules/filters/a_filter/a_filter.css, src/frontend/src/modules/filters/a_filter/a_filter.js, src/frontend/src/modules/filters/out_filter/out_filter.css, src/frontend/src/modules/filters/out_filter/out_filter.js, src/frontend/src/modules/filters/rf_filter/rf_filter.css, src/frontend/src/modules/filters/rf_filter/rf_filter.js, src/frontend/src/modules/filters/v_filter/filter.css, src/frontend/src/modules/filters/v_filter/filter.js
Coordinator overview page is no longer scrollable. Filter buttons moved to correct location
=> Moved the filter button so the coord overview page not scrollable

package-lock.json, package.json, src/api/utils.py, src/frontend/src/modules/admin/adminAddSite/index.js, src/frontend/src/modules/admin/adminHomepage/index.js, src/frontend/src/modules/admin/adminViewSite/index.js, src/frontend/src/modules/coords/detailView/index.js, src/frontend/src/modules/coords/siteAddCase/index.js, src/frontend/src/modules/coords/siteAddCase/styles.css, src/frontend/src/modules/coords/siteOverview/index.js, src/frontend/src/modules/logIn/AdminRoute.js, src/frontend/src/modules/logIn/CoordRoute.js, src/frontend/src/modules/logIn/Loading.js
Added spinning loading icon to various pages
=> Icon loading

src/frontend/src/modules/admin/adminHomepage/index.js, src/frontend/src/modules/admin/adminHomepage/styles.css, src/frontend/src/modules/coords/siteOverview/index.js, src/frontend/src/modules/overviewTable/overviewTable.js
Added pagination on admin and coord home pages.
=> Pagination

src/api/views.py, src/frontend/src/modules/logIn/index.js
Removed deprecated code in backend and added reset of cookies on login page.
=> Error login
